// Pino sync — single-blob store keyed by a secret sync key.
//
// Model: the app is local-first; this Worker is just the relay between a
// user's devices. Auth == knowledge of the sync key (a 128-bit+ random string
// generated by the app). The key never touches disk here — only its SHA-256
// hash is used as the KV key, so a KV dump alone can't be replayed as auth.
//
// API (all responses JSON):
//   GET /state              → { rev, updatedAt, blob }   (rev 0 / blob null if new)
//   PUT /state { baseRev, blob }
//        → 200 { rev }                        when baseRev matches stored rev
//        → 409 { rev, updatedAt, blob }       stale baseRev — merge this and retry
//
// NOTE: KV is eventually consistent across edge locations (~60 s worst case).
// The client always pulls + merges before pushing and every device keeps the
// full state locally, so a stale read can only delay convergence, not lose data.

const ALLOWED_ORIGINS = [
  'https://kevinamato.github.io',
  'http://localhost:5173',
  'http://127.0.0.1:5173',
];

const MAX_BLOB_BYTES = 400_000; // board blob is ~10-100 KB; hard stop well above

// Free-tier guard: Cloudflare KV allows 1,000 writes/day across the WHOLE
// namespace, shared by every board. 250/board keeps a few active shared
// workspaces comfortably inside it; the counter piggybacks on the state
// record itself so enforcing it costs zero extra KV operations. The client
// keeps working locally on 429 and retries tomorrow.
const MAX_WRITES_PER_DAY = 250;

function corsHeaders(req) {
  const origin = req.headers.get('Origin') || '';
  return {
    'Access-Control-Allow-Origin': ALLOWED_ORIGINS.includes(origin) ? origin : ALLOWED_ORIGINS[0],
    'Access-Control-Allow-Methods': 'GET,PUT,OPTIONS',
    'Access-Control-Allow-Headers': 'Content-Type,X-Sync-Key',
    'Access-Control-Max-Age': '86400',
    Vary: 'Origin',
  };
}

const json = (obj, status, cors) =>
  new Response(JSON.stringify(obj), {
    status,
    headers: { ...cors, 'Content-Type': 'application/json' },
  });

async function kvKeyFor(syncKey) {
  const digest = await crypto.subtle.digest('SHA-256', new TextEncoder().encode(syncKey));
  return (
    'state:' +
    [...new Uint8Array(digest)].map((b) => b.toString(16).padStart(2, '0')).join('')
  );
}

export default {
  async fetch(req, env) {
    const cors = corsHeaders(req);
    if (req.method === 'OPTIONS') return new Response(null, { status: 204, headers: cors });

    const url = new URL(req.url);
    if (url.pathname !== '/state') return json({ error: 'not found' }, 404, cors);

    const syncKey = req.headers.get('X-Sync-Key') || '';
    if (syncKey.length < 16) return json({ error: 'missing or invalid sync key' }, 401, cors);
    const kvKey = await kvKeyFor(syncKey);

    if (req.method === 'GET') {
      const stored = await env.STATE.get(kvKey);
      if (!stored) return json({ rev: 0, updatedAt: null, blob: null }, 200, cors);
      return new Response(stored, { headers: { ...cors, 'Content-Type': 'application/json' } });
    }

    if (req.method === 'PUT') {
      const text = await req.text();
      if (text.length > MAX_BLOB_BYTES) return json({ error: 'blob too large' }, 413, cors);
      let body;
      try {
        body = JSON.parse(text);
      } catch {
        return json({ error: 'invalid JSON' }, 400, cors);
      }
      if (typeof body?.baseRev !== 'number' || !body.blob || typeof body.blob !== 'object') {
        return json({ error: 'expected { baseRev, blob }' }, 400, cors);
      }

      const stored = await env.STATE.get(kvKey, 'json');
      const currentRev = stored?.rev || 0;
      if (body.baseRev !== currentRev) {
        // Stale base — hand back the current server state so the client can
        // merge once more and retry without an extra round-trip.
        return json(
          { rev: currentRev, updatedAt: stored?.updatedAt || null, blob: stored?.blob || null },
          409,
          cors,
        );
      }

      const today = new Date().toISOString().slice(0, 10);
      const writesToday = stored?.writes?.day === today ? stored.writes.n : 0;
      if (writesToday >= MAX_WRITES_PER_DAY) {
        return json({ error: 'daily write limit reached — try again tomorrow' }, 429, cors);
      }

      const next = {
        rev: currentRev + 1,
        updatedAt: new Date().toISOString(),
        blob: body.blob,
        writes: { day: today, n: writesToday + 1 },
      };
      await env.STATE.put(kvKey, JSON.stringify(next));
      return json({ rev: next.rev }, 200, cors);
    }

    return json({ error: 'method not allowed' }, 405, cors);
  },
};
